-- MySQL Script generated by MySQL Workbench
-- Mon Jul  1 17:18:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema silicon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `silicon` ;

-- -----------------------------------------------------
-- Schema silicon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `silicon` DEFAULT CHARACTER SET utf8 ;
USE `silicon` ;

-- -----------------------------------------------------
-- Table `silicon`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `silicon`.`groups` ;

CREATE TABLE IF NOT EXISTS `silicon`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silicon`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `silicon`.`users` ;

CREATE TABLE IF NOT EXISTS `silicon`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `group_id` INT NOT NULL DEFAULT 1,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `group_id`),
  INDEX `fk_users_groups_idx` (`group_id` ASC),
  CONSTRAINT `fk_users_groups`
    FOREIGN KEY (`group_id`)
    REFERENCES `silicon`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `silicon`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `silicon`.`login` ;

CREATE TABLE IF NOT EXISTS `silicon`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `kind` ENUM('admin', 'employee') NULL DEFAULT 'employee',
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `silicon`.`groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `silicon`;
INSERT INTO `silicon`.`groups` (`id`, `name`, `created`, `updated`) VALUES (DEFAULT, 'Ungrouped', DEFAULT, DEFAULT);
INSERT INTO `silicon`.`groups` (`id`, `name`, `created`, `updated`) VALUES (DEFAULT, 'Merchant', DEFAULT, DEFAULT);
INSERT INTO `silicon`.`groups` (`id`, `name`, `created`, `updated`) VALUES (DEFAULT, 'Subscriber', DEFAULT, DEFAULT);
INSERT INTO `silicon`.`groups` (`id`, `name`, `created`, `updated`) VALUES (DEFAULT, 'Underwriter', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `silicon`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `silicon`;
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'kola', 1, DEFAULT, DEFAULT);
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'james', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'ben', 3, DEFAULT, DEFAULT);
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'bob', 2, DEFAULT, DEFAULT);
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'dan', 4, DEFAULT, DEFAULT);
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'jane', 3, DEFAULT, DEFAULT);
INSERT INTO `silicon`.`users` (`id`, `name`, `group_id`, `created`, `updated`) VALUES (DEFAULT, 'sam', 2, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `silicon`.`login`
-- -----------------------------------------------------
START TRANSACTION;
USE `silicon`;
INSERT INTO `silicon`.`login` (`id`, `name`, `kind`, `email`, `password`, `created`, `updated`) VALUES (DEFAULT, 'admin', 'admin', 'admin@example.com', '$2y$12$OgfVoHLGmKucgqmFWVIy5erOZxNoSO78AcsMFtVZkfnYA/xk0biRu', DEFAULT, DEFAULT);
INSERT INTO `silicon`.`login` (`id`, `name`, `kind`, `email`, `password`, `created`, `updated`) VALUES (DEFAULT, 'worker', 'employee', 'worker@example.com', '$2y$12$OgfVoHLGmKucgqmFWVIy5erOZxNoSO78AcsMFtVZkfnYA/xk0biRu', DEFAULT, DEFAULT);

COMMIT;

